### ISSUE TITLE
Manage bookings

### ISSUE THREAD

**Issue by SuzanDewitz** [SuzanDewitz/TableFinder#1]
## User story

As a Customer I can click on "my booking page" so that I can make changes to my bookings at the restaurant
___
## Acceptance Criteria:

 - Display a my bookings link in the navbar for easy access.
 - Display a list of all the bookings and a link to delete or update the booking.
 - Display a pop-up message to confirm changes.

___
## Tasks:
 - [ ] Create the my booking link in the navbar
 - [ ]Create the my bookings model
 - [ ]  Create the views function for the my bookings page
 - [ ] Create the my bookings page HTML & CSS

**Comment by SuzanDewitz** [comment]
As a frequent  ** customer**, I want to receive real-time flight updates, so that I can stay informed about any changes or delays to my itinerary.
