### ISSUE TITLE
View menu items 

### ISSUE THREAD

**Issue by SuzanDewitz** [SuzanDewitz/TableFinder#7]
## User story

As a Customer I can view a page that shows the menu so that I can decide what I want to order
___
## Acceptance Criteria:

 - Customer can find the menu on the main page.
 - Customer can view the menu and read it's content.

___
## Tasks:
 - [ ] Create menu page
 - [ ] Create menu items
 - [ ]  Create link to menu page on mainpage.
 - [ ]  Create link to menu page in navbar.
