### ISSUE TITLE
Booking page

### ISSUE THREAD

**Issue by SuzanDewitz** [SuzanDewitz/TableFinder#9]
## User story

As a Customer I can click on a booking page so that I can make my reservation at the restaurant
___
## Acceptance Criteria:

 - Display a booking link on hero section.
 - Display a booking link in the navbar for easy access.
- Display booking options to Customer, based on guests, date and time.
- Display a pop-up message to confirm booking.

 

___
## Tasks:
 - [ ] Create the booking link in the hero page
 - [ ] Create the booking link in the navbar
 - [ ] Create the bookings model
 - [ ] Create the views function for the bookings page
 - [ ] Create the bookings page HTML & CSS
